### ISSUE TITLE
Quota of LocalStorage exceeded

### ISSUE THREAD

**Issue by christianrank** [nickbaum/simple-window-saver#43]
I have around 380 Tabs saved in about 10 windows, which should be absolutely no problem, but suddenly the extension stopped working completely.

```
Error handling response: Error: Failed to set a named property on 'Storage': Setting the value of 'Window' exceeded the quota.
    at storeWindow (chrome-extension://fpfmklldfnlcblofkhdeoohfppdoejdc/background.js:149:22)
    at saveWindow (chrome-extension://fpfmklldfnlcblofkhdeoohfppdoejdc/background.js:133:3)
    at chrome-extension://fpfmklldfnlcblofkhdeoohfppdoejdc/popup.js:93:36
```

It should use another way of storage, LocalStorage is not made for anything this large.

**Comment by elcoms** [comment]
Could be solved if we could allow unlimitedStorage for this extension

> Note: The chrome.storage.local can only store a limited amount. Can you check if the saved data is not higher than this quota bytes:
> QUOTA_BYTES 5242880
> The maximum amount (in bytes) of data that can be stored in local storage, as measured by the JSON stringification of every value plus every key's length. This value will be ignored if the extension has the unlimitedStorage permission. Updates that would cause this limit to be exceeded fail immediately and set runtime.lastError.
> Source: https://developer.chrome.com/docs/extensions/reference/storage/#property-local
